export const DATA_SOURCE = 'DATA_SOURCE';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';
export const COURSE_SECTION_REPOSITORY = 'COURSE_SECTION_REPOSITORY';
export const CLASS_SCHEDULE_REPOSITORY = 'CLASS_SCHEDULE_REPOSITORY';
export const INSTRUCTOR_REPOSITORY = 'INSTRUCTOR_REPOSITORY';
export const REGISTRATION_REPOSITORY = 'REGISTRATION_REPOSITORY';
export const EXCHANGE_REQUEST_REPOSITORY = 'EXCHANGE_REQUEST_REPOSITORY';
export const TEMPORARY_REPOSITORY = 'TEMPORARY_REPOSITORY';
export const COHORT_REPOSITORY = 'COHORT_REPOSITORY';
export const STUDENT_REPOSITORY = 'STUDENT_REPOSITORY';
export const SEMESTER_REPOSITORY = 'SEMESTER_REPOSITORY';
export const COURSE_REGISTRATION_PERIOD_REPOSITORY = 'COURSE_REGISTRATION_PERIOD_REPOSITORY';